### ISSUE TITLE
Basic Routes To be Implemented

### ISSUE THREAD

**Issue by timzprof** [markessien/socialapp#1]
### Routes

- **GET** Timeline(Homepage)
- **GET** User Profile 
- **POST** Login
- **POST** Sign Up
- **POST** Post Comment
- **POST** Upload Pictures, Images and Videos
- **PUT** Update User Profile
- **PUT** Reset User Password
- **DELETE** Delete User Account

**Comment by Legendary-Tony** [comment]
I am done with this tasks
