### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by KingAviator** [markessien/socialapp#19]
**Add authentication to user registration
Unsuccessful signups should fallback to the signup page
Successful registrations should navigate to the apps homepage**

**Comment by Legendary-Tony** [comment]
What the problem so that I can work on it....

**Comment by KingAviator** [comment]
I marked it as a new feature to be implemented
Read more on the description of the problem

**Comment by Legendary-Tony** [comment]
I want to work on this ....pls confirm the duplicate migration I sent to you.....

**Comment by RaphAlemoh** [comment]
mine is showing duplicate too

**Comment by RaphAlemoh** [comment]
checked upload i did the authentication already

**Comment by RaphAlemoh** [comment]
am actually looking for the views folder so i can do the routing stuff
and admin too

**Comment by Legendary-Tony** [comment]
Am done the routing already and it has been merge...but this people get problem of closing issue that has been fixed

**Comment by thecodearcher** [comment]
I am closing this issue because the auth has been genrated with laravel auth command.
