### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by KingAviator** [markessien/socialapp#20]
**Verify user login
Unsuccessful logins should display an error message with reasons for failure
Successful logins should navigate to the apps homepage**

**Comment by Legendary-Tony** [comment]
KingAviator......what is the issue

**Comment by KingAviator** [comment]
Implement the features

**Comment by RaphAlemoh** [comment]
check my request i did.. you need php artisan make:auth
are you are 70% done with the registration part

**Comment by thecodearcher** [comment]
I am closing this issue because the auth has been generated with laravel auth command
